// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1CpT15JA-qVrV1BLqi98g5rMoP6MA3HY',
    appId: '1:840529050371:web:a7eed996b70ee998b84736',
    messagingSenderId: '840529050371',
    projectId: 'snoreclinics-ai',
    authDomain: 'snoreclinics-ai.firebaseapp.com',
    storageBucket: 'snoreclinics-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpXHSGiU4mObeVgNkVZEuxLm1Qrvyyuj0',
    appId: '1:840529050371:android:0f29726ad41e9c51b84736',
    messagingSenderId: '840529050371',
    projectId: 'snoreclinics-ai',
    storageBucket: 'snoreclinics-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0yQo-D9UPQiyU19sGubOE6s0AvJpDN5I',
    appId: '1:840529050371:ios:36e61a2cfbdec00db84736',
    messagingSenderId: '840529050371',
    projectId: 'snoreclinics-ai',
    storageBucket: 'snoreclinics-ai.firebasestorage.app',
    iosBundleId: 'com.example.sleepAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0yQo-D9UPQiyU19sGubOE6s0AvJpDN5I',
    appId: '1:840529050371:ios:36e61a2cfbdec00db84736',
    messagingSenderId: '840529050371',
    projectId: 'snoreclinics-ai',
    storageBucket: 'snoreclinics-ai.firebasestorage.app',
    iosBundleId: 'com.example.sleepAnalyzer',
  );
}
